export enum FruitTag {
  Sugar = 'SUGAR',
  Red = 'RED',
  Leaf = 'LEAF',
  Small = 'SMALL',
  Nut = 'NUT',
  Flower = 'FLOWER',
  Agrume = 'AGRUME',
  Green = 'GREEN',
  Liane = 'LIANE',
  Alien = 'ALIEN',
  Berries = 'BERRIES',
  Long = 'LONG',
  Courge = 'COURGE',
  Poire = 'POIRE',
  Blue = 'BLUE',
  Apple = 'APPLE',
  Shit = 'SHIT',
  Orange = 'ORANGE',
  Yellow = 'YELLOW',
  Pink = 'PINK'
}
